services:
  - type: web
    name: company-saas-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://company-saas-blvpjp5hp-manishs-projects-79623ce3.vercel.app
      - key: NEXT_PUBLIC_SUPABASE_URL
        fromDatabase:
          name: supabase
          property: connectionString
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        fromDatabase:
          name: supabase
          property: anonKey
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromDatabase:
          name: supabase
          property: serviceRoleKey
    healthCheckPath: /api/health
    autoDeploy: true
